"""Add highlight field to job applications

Revision ID: 3ad00d3494db
Revises: 6d6432c6e85c
Create Date: 2025-02-19 16:21:34.562747

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3ad00d3494db'
down_revision = '6d6432c6e85c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('job_application', schema=None) as batch_op:
        batch_op.add_column(sa.Column('highlight', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('job_application', schema=None) as batch_op:
        batch_op.drop_column('highlight')

    # ### end Alembic commands ###
