"""Add InterviewStage model

Revision ID: 6d6432c6e85c
Revises: cd6d8fa2f119
Create Date: 2025-01-05 09:45:18.173018

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6d6432c6e85c'
down_revision = 'cd6d8fa2f119'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('interview_stage',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_application_id', sa.Integer(), nullable=False),
    sa.Column('stage_name', sa.String(length=100), nullable=False),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['job_application_id'], ['job_application.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('interview_stage')
    # ### end Alembic commands ###
