"""Make date_submitted optional

Revision ID: 9344a9ccc98d
Revises: cce6392f124d
Create Date: 2025-01-03 19:46:44.865856

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9344a9ccc98d'
down_revision = 'cce6392f124d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('job_application', schema=None) as batch_op:
        batch_op.alter_column('date_submitted',
               existing_type=sa.DATE(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('job_application', schema=None) as batch_op:
        batch_op.alter_column('date_submitted',
               existing_type=sa.DATE(),
               nullable=False)

    # ### end Alembic commands ###
